/**
 * Smithers TUI feature inventory.
 *
 * This spec is grounded in:
 * - docs/smithers-tui/01-PRD.md
 * - docs/smithers-tui/02-DESIGN.md
 * - docs/smithers-tui/03-ENGINEERING.md
 *
 * Focus: Smithers-specific functionality being added on top of Crush.
 * It intentionally excludes generic Crush capabilities that already existed
 * before the Smithers fork unless the Smithers docs define a Smithers-specific
 * extension or behavior.
 */

export enum SmithersFeature {
  PLATFORM_SMITHERS_REBRAND = "PLATFORM_SMITHERS_REBRAND",
  PLATFORM_SMITHERS_CONFIG_NAMESPACE = "PLATFORM_SMITHERS_CONFIG_NAMESPACE",
  PLATFORM_THIN_FRONTEND_TRANSPORT_LAYER = "PLATFORM_THIN_FRONTEND_TRANSPORT_LAYER",
  PLATFORM_HTTP_API_CLIENT = "PLATFORM_HTTP_API_CLIENT",
  PLATFORM_SSE_EVENT_STREAMING = "PLATFORM_SSE_EVENT_STREAMING",
  PLATFORM_MCP_TRANSPORT = "PLATFORM_MCP_TRANSPORT",
  PLATFORM_SHELL_OUT_FALLBACK = "PLATFORM_SHELL_OUT_FALLBACK",
  PLATFORM_CHAT_FIRST_INFORMATION_ARCHITECTURE = "PLATFORM_CHAT_FIRST_INFORMATION_ARCHITECTURE",
  PLATFORM_WORKSPACE_AND_SYSTEMS_VIEW_MODEL = "PLATFORM_WORKSPACE_AND_SYSTEMS_VIEW_MODEL",
  PLATFORM_VIEW_STACK_ROUTER = "PLATFORM_VIEW_STACK_ROUTER",
  PLATFORM_BACK_STACK_NAVIGATION = "PLATFORM_BACK_STACK_NAVIGATION",
  PLATFORM_KEYBOARD_FIRST_NAVIGATION = "PLATFORM_KEYBOARD_FIRST_NAVIGATION",
  PLATFORM_SMITHERS_COMMAND_PALETTE_EXTENSIONS = "PLATFORM_SMITHERS_COMMAND_PALETTE_EXTENSIONS",
  PLATFORM_SPLIT_PANE_LAYOUTS = "PLATFORM_SPLIT_PANE_LAYOUTS",

  CHAT_SMITHERS_DEFAULT_CONSOLE = "CHAT_SMITHERS_DEFAULT_CONSOLE",
  CHAT_SMITHERS_SPECIALIZED_AGENT = "CHAT_SMITHERS_SPECIALIZED_AGENT",
  CHAT_SMITHERS_DOMAIN_SYSTEM_PROMPT = "CHAT_SMITHERS_DOMAIN_SYSTEM_PROMPT",
  CHAT_SMITHERS_WORKSPACE_CONTEXT_DISCOVERY = "CHAT_SMITHERS_WORKSPACE_CONTEXT_DISCOVERY",
  CHAT_SMITHERS_ACTIVE_RUN_SUMMARY = "CHAT_SMITHERS_ACTIVE_RUN_SUMMARY",
  CHAT_SMITHERS_PENDING_APPROVAL_SUMMARY = "CHAT_SMITHERS_PENDING_APPROVAL_SUMMARY",
  CHAT_SMITHERS_MCP_CONNECTION_STATUS = "CHAT_SMITHERS_MCP_CONNECTION_STATUS",
  CHAT_SMITHERS_HELPBAR_SHORTCUTS = "CHAT_SMITHERS_HELPBAR_SHORTCUTS",
  CHAT_SMITHERS_CUSTOM_TOOL_RENDERERS = "CHAT_SMITHERS_CUSTOM_TOOL_RENDERERS",

  RUNS_DASHBOARD = "RUNS_DASHBOARD",
  RUNS_STATUS_SECTIONING = "RUNS_STATUS_SECTIONING",
  RUNS_REALTIME_STATUS_UPDATES = "RUNS_REALTIME_STATUS_UPDATES",
  RUNS_INLINE_RUN_DETAILS = "RUNS_INLINE_RUN_DETAILS",
  RUNS_PROGRESS_VISUALIZATION = "RUNS_PROGRESS_VISUALIZATION",
  RUNS_FILTER_BY_STATUS = "RUNS_FILTER_BY_STATUS",
  RUNS_FILTER_BY_WORKFLOW = "RUNS_FILTER_BY_WORKFLOW",
  RUNS_FILTER_BY_DATE_RANGE = "RUNS_FILTER_BY_DATE_RANGE",
  RUNS_SEARCH = "RUNS_SEARCH",
  RUNS_QUICK_APPROVE = "RUNS_QUICK_APPROVE",
  RUNS_QUICK_DENY = "RUNS_QUICK_DENY",
  RUNS_QUICK_CANCEL = "RUNS_QUICK_CANCEL",
  RUNS_QUICK_HIJACK = "RUNS_QUICK_HIJACK",
  RUNS_OPEN_LIVE_CHAT = "RUNS_OPEN_LIVE_CHAT",
  RUNS_INSPECT_SUMMARY = "RUNS_INSPECT_SUMMARY",
  RUNS_DAG_OVERVIEW = "RUNS_DAG_OVERVIEW",
  RUNS_NODE_INSPECTOR = "RUNS_NODE_INSPECTOR",
  RUNS_TASK_TAB_INPUT = "RUNS_TASK_TAB_INPUT",
  RUNS_TASK_TAB_OUTPUT = "RUNS_TASK_TAB_OUTPUT",
  RUNS_TASK_TAB_CONFIG = "RUNS_TASK_TAB_CONFIG",
  RUNS_TASK_TAB_CHAT_LOGS = "RUNS_TASK_TAB_CHAT_LOGS",

  LIVE_CHAT_VIEWER = "LIVE_CHAT_VIEWER",
  LIVE_CHAT_STREAMING_OUTPUT = "LIVE_CHAT_STREAMING_OUTPUT",
  LIVE_CHAT_RELATIVE_TIMESTAMPS = "LIVE_CHAT_RELATIVE_TIMESTAMPS",
  LIVE_CHAT_ATTEMPT_TRACKING = "LIVE_CHAT_ATTEMPT_TRACKING",
  LIVE_CHAT_RETRY_HISTORY = "LIVE_CHAT_RETRY_HISTORY",
  LIVE_CHAT_TOOL_CALL_RENDERING = "LIVE_CHAT_TOOL_CALL_RENDERING",
  LIVE_CHAT_FOLLOW_MODE = "LIVE_CHAT_FOLLOW_MODE",
  LIVE_CHAT_SIDE_BY_SIDE_CONTEXT = "LIVE_CHAT_SIDE_BY_SIDE_CONTEXT",
  HIJACK_RUN_COMMAND = "HIJACK_RUN_COMMAND",
  HIJACK_SEAMLESS_TRANSITION = "HIJACK_SEAMLESS_TRANSITION",
  HIJACK_NATIVE_CLI_RESUME = "HIJACK_NATIVE_CLI_RESUME",
  HIJACK_CONVERSATION_REPLAY_FALLBACK = "HIJACK_CONVERSATION_REPLAY_FALLBACK",
  HIJACK_MULTI_ENGINE_SUPPORT = "HIJACK_MULTI_ENGINE_SUPPORT",
  HIJACK_RESUME_TO_AUTOMATION = "HIJACK_RESUME_TO_AUTOMATION",

  APPROVALS_PENDING_BADGES = "APPROVALS_PENDING_BADGES",
  APPROVALS_QUEUE = "APPROVALS_QUEUE",
  APPROVALS_INLINE_APPROVE = "APPROVALS_INLINE_APPROVE",
  APPROVALS_INLINE_DENY = "APPROVALS_INLINE_DENY",
  APPROVALS_CONTEXT_DISPLAY = "APPROVALS_CONTEXT_DISPLAY",
  APPROVALS_RECENT_DECISIONS = "APPROVALS_RECENT_DECISIONS",
  NOTIFICATIONS_TOAST_OVERLAYS = "NOTIFICATIONS_TOAST_OVERLAYS",
  NOTIFICATIONS_APPROVAL_REQUESTS = "NOTIFICATIONS_APPROVAL_REQUESTS",
  NOTIFICATIONS_RUN_FAILURES = "NOTIFICATIONS_RUN_FAILURES",
  NOTIFICATIONS_RUN_COMPLETIONS = "NOTIFICATIONS_RUN_COMPLETIONS",

  TIME_TRAVEL_TIMELINE_VIEW = "TIME_TRAVEL_TIMELINE_VIEW",
  TIME_TRAVEL_SNAPSHOT_MARKERS = "TIME_TRAVEL_SNAPSHOT_MARKERS",
  TIME_TRAVEL_SNAPSHOT_INSPECTOR = "TIME_TRAVEL_SNAPSHOT_INSPECTOR",
  TIME_TRAVEL_SNAPSHOT_DIFF = "TIME_TRAVEL_SNAPSHOT_DIFF",
  TIME_TRAVEL_FORK_FROM_SNAPSHOT = "TIME_TRAVEL_FORK_FROM_SNAPSHOT",
  TIME_TRAVEL_REPLAY_FROM_SNAPSHOT = "TIME_TRAVEL_REPLAY_FROM_SNAPSHOT",

  WORKFLOWS_LIST = "WORKFLOWS_LIST",
  WORKFLOWS_DISCOVERY_FROM_PROJECT = "WORKFLOWS_DISCOVERY_FROM_PROJECT",
  WORKFLOWS_RUN = "WORKFLOWS_RUN",
  WORKFLOWS_DYNAMIC_INPUT_FORMS = "WORKFLOWS_DYNAMIC_INPUT_FORMS",
  WORKFLOWS_DAG_INSPECTION = "WORKFLOWS_DAG_INSPECTION",
  WORKFLOWS_AGENT_AND_SCHEMA_INSPECTION = "WORKFLOWS_AGENT_AND_SCHEMA_INSPECTION",
  WORKFLOWS_DOCTOR = "WORKFLOWS_DOCTOR",

  AGENTS_BROWSER = "AGENTS_BROWSER",
  AGENTS_CLI_DETECTION = "AGENTS_CLI_DETECTION",
  AGENTS_BINARY_PATH_DISPLAY = "AGENTS_BINARY_PATH_DISPLAY",
  AGENTS_AVAILABILITY_STATUS = "AGENTS_AVAILABILITY_STATUS",
  AGENTS_AUTH_STATUS_CLASSIFICATION = "AGENTS_AUTH_STATUS_CLASSIFICATION",
  AGENTS_ROLE_DISPLAY = "AGENTS_ROLE_DISPLAY",
  AGENTS_DIRECT_CHAT = "AGENTS_DIRECT_CHAT",

  TICKETS_LIST = "TICKETS_LIST",
  TICKETS_DETAIL_VIEW = "TICKETS_DETAIL_VIEW",
  TICKETS_CREATE = "TICKETS_CREATE",
  TICKETS_EDIT_INLINE = "TICKETS_EDIT_INLINE",
  TICKETS_SPLIT_PANE_LAYOUT = "TICKETS_SPLIT_PANE_LAYOUT",
  PROMPTS_LIST = "PROMPTS_LIST",
  PROMPTS_SOURCE_EDIT = "PROMPTS_SOURCE_EDIT",
  PROMPTS_EXTERNAL_EDITOR_HANDOFF = "PROMPTS_EXTERNAL_EDITOR_HANDOFF",
  PROMPTS_PROPS_DISCOVERY = "PROMPTS_PROPS_DISCOVERY",
  PROMPTS_LIVE_PREVIEW = "PROMPTS_LIVE_PREVIEW",
  PROMPTS_SAVE = "PROMPTS_SAVE",

  SQL_BROWSER = "SQL_BROWSER",
  SQL_TABLE_SIDEBAR = "SQL_TABLE_SIDEBAR",
  SQL_QUERY_EDITOR = "SQL_QUERY_EDITOR",
  SQL_RESULTS_TABLE = "SQL_RESULTS_TABLE",
  TRIGGERS_LIST = "TRIGGERS_LIST",
  TRIGGERS_TOGGLE = "TRIGGERS_TOGGLE",
  TRIGGERS_CREATE = "TRIGGERS_CREATE",
  TRIGGERS_EDIT = "TRIGGERS_EDIT",
  TRIGGERS_DELETE = "TRIGGERS_DELETE",
  SCORES_AND_ROI_DASHBOARD = "SCORES_AND_ROI_DASHBOARD",
  SCORES_RUN_EVALUATIONS = "SCORES_RUN_EVALUATIONS",
  SCORES_TOKEN_USAGE_METRICS = "SCORES_TOKEN_USAGE_METRICS",
  SCORES_TOOL_CALL_METRICS = "SCORES_TOOL_CALL_METRICS",
  SCORES_LATENCY_METRICS = "SCORES_LATENCY_METRICS",
  SCORES_CACHE_EFFICIENCY_METRICS = "SCORES_CACHE_EFFICIENCY_METRICS",
  SCORES_DAILY_AND_WEEKLY_SUMMARIES = "SCORES_DAILY_AND_WEEKLY_SUMMARIES",
  SCORES_COST_TRACKING = "SCORES_COST_TRACKING",
  MEMORY_BROWSER = "MEMORY_BROWSER",
  MEMORY_FACT_LIST = "MEMORY_FACT_LIST",
  MEMORY_SEMANTIC_RECALL = "MEMORY_SEMANTIC_RECALL",
  MEMORY_CROSS_RUN_MESSAGE_HISTORY = "MEMORY_CROSS_RUN_MESSAGE_HISTORY",

  MCP_TOOL_DISCOVERY_FROM_SMITHERS_SERVER = "MCP_TOOL_DISCOVERY_FROM_SMITHERS_SERVER",
  MCP_RUNS_TOOLS = "MCP_RUNS_TOOLS",
  MCP_OBSERVABILITY_TOOLS = "MCP_OBSERVABILITY_TOOLS",
  MCP_CONTROL_TOOLS = "MCP_CONTROL_TOOLS",
  MCP_TIME_TRAVEL_TOOLS = "MCP_TIME_TRAVEL_TOOLS",
  MCP_WORKFLOW_TOOLS = "MCP_WORKFLOW_TOOLS",
  MCP_AGENT_TOOLS = "MCP_AGENT_TOOLS",
  MCP_TICKET_TOOLS = "MCP_TICKET_TOOLS",
  MCP_PROMPT_TOOLS = "MCP_PROMPT_TOOLS",
  MCP_MEMORY_TOOLS = "MCP_MEMORY_TOOLS",
  MCP_SCORING_TOOLS = "MCP_SCORING_TOOLS",
  MCP_CRON_TOOLS = "MCP_CRON_TOOLS",
  MCP_SQL_TOOLS = "MCP_SQL_TOOLS",
}

export const SmithersFeatureGroups = {
  // Source: PRD sections 7-9, Design sections 1-2 and 3.13, Engineering
  // sections 2-3.
  PLATFORM_AND_NAVIGATION: [
    SmithersFeature.PLATFORM_SMITHERS_REBRAND,
    SmithersFeature.PLATFORM_SMITHERS_CONFIG_NAMESPACE,
    SmithersFeature.PLATFORM_THIN_FRONTEND_TRANSPORT_LAYER,
    SmithersFeature.PLATFORM_HTTP_API_CLIENT,
    SmithersFeature.PLATFORM_SSE_EVENT_STREAMING,
    SmithersFeature.PLATFORM_MCP_TRANSPORT,
    SmithersFeature.PLATFORM_SHELL_OUT_FALLBACK,
    SmithersFeature.PLATFORM_CHAT_FIRST_INFORMATION_ARCHITECTURE,
    SmithersFeature.PLATFORM_WORKSPACE_AND_SYSTEMS_VIEW_MODEL,
    SmithersFeature.PLATFORM_VIEW_STACK_ROUTER,
    SmithersFeature.PLATFORM_BACK_STACK_NAVIGATION,
    SmithersFeature.PLATFORM_KEYBOARD_FIRST_NAVIGATION,
    SmithersFeature.PLATFORM_SMITHERS_COMMAND_PALETTE_EXTENSIONS,
    SmithersFeature.PLATFORM_SPLIT_PANE_LAYOUTS,
  ],

  // Source: PRD section 6.1, Design section 3.1, Engineering sections 3.0-3.1.
  CHAT_AND_CONSOLE: [
    SmithersFeature.CHAT_SMITHERS_DEFAULT_CONSOLE,
    SmithersFeature.CHAT_SMITHERS_SPECIALIZED_AGENT,
    SmithersFeature.CHAT_SMITHERS_DOMAIN_SYSTEM_PROMPT,
    SmithersFeature.CHAT_SMITHERS_WORKSPACE_CONTEXT_DISCOVERY,
    SmithersFeature.CHAT_SMITHERS_ACTIVE_RUN_SUMMARY,
    SmithersFeature.CHAT_SMITHERS_PENDING_APPROVAL_SUMMARY,
    SmithersFeature.CHAT_SMITHERS_MCP_CONNECTION_STATUS,
    SmithersFeature.CHAT_SMITHERS_HELPBAR_SHORTCUTS,
    SmithersFeature.CHAT_SMITHERS_CUSTOM_TOOL_RENDERERS,
  ],

  // Source: PRD sections 6.2 and 6.7, Design sections 3.2, 3.11, 3.12,
  // and 3.14, Engineering section 3.1.
  RUNS_AND_INSPECTION: [
    SmithersFeature.RUNS_DASHBOARD,
    SmithersFeature.RUNS_STATUS_SECTIONING,
    SmithersFeature.RUNS_REALTIME_STATUS_UPDATES,
    SmithersFeature.RUNS_INLINE_RUN_DETAILS,
    SmithersFeature.RUNS_PROGRESS_VISUALIZATION,
    SmithersFeature.RUNS_FILTER_BY_STATUS,
    SmithersFeature.RUNS_FILTER_BY_WORKFLOW,
    SmithersFeature.RUNS_FILTER_BY_DATE_RANGE,
    SmithersFeature.RUNS_SEARCH,
    SmithersFeature.RUNS_QUICK_APPROVE,
    SmithersFeature.RUNS_QUICK_DENY,
    SmithersFeature.RUNS_QUICK_CANCEL,
    SmithersFeature.RUNS_QUICK_HIJACK,
    SmithersFeature.RUNS_OPEN_LIVE_CHAT,
    SmithersFeature.RUNS_INSPECT_SUMMARY,
    SmithersFeature.RUNS_DAG_OVERVIEW,
    SmithersFeature.RUNS_NODE_INSPECTOR,
    SmithersFeature.RUNS_TASK_TAB_INPUT,
    SmithersFeature.RUNS_TASK_TAB_OUTPUT,
    SmithersFeature.RUNS_TASK_TAB_CONFIG,
    SmithersFeature.RUNS_TASK_TAB_CHAT_LOGS,
  ],

  // Source: PRD sections 6.3-6.4, Design sections 3.3-3.4, Engineering
  // section 3.2.
  LIVE_CHAT_AND_HIJACK: [
    SmithersFeature.LIVE_CHAT_VIEWER,
    SmithersFeature.LIVE_CHAT_STREAMING_OUTPUT,
    SmithersFeature.LIVE_CHAT_RELATIVE_TIMESTAMPS,
    SmithersFeature.LIVE_CHAT_ATTEMPT_TRACKING,
    SmithersFeature.LIVE_CHAT_RETRY_HISTORY,
    SmithersFeature.LIVE_CHAT_TOOL_CALL_RENDERING,
    SmithersFeature.LIVE_CHAT_FOLLOW_MODE,
    SmithersFeature.LIVE_CHAT_SIDE_BY_SIDE_CONTEXT,
    SmithersFeature.HIJACK_RUN_COMMAND,
    SmithersFeature.HIJACK_SEAMLESS_TRANSITION,
    SmithersFeature.HIJACK_NATIVE_CLI_RESUME,
    SmithersFeature.HIJACK_CONVERSATION_REPLAY_FALLBACK,
    SmithersFeature.HIJACK_MULTI_ENGINE_SUPPORT,
    SmithersFeature.HIJACK_RESUME_TO_AUTOMATION,
  ],

  // Source: PRD section 6.5, Design sections 3.5 and 3.15, Engineering
  // section 3.2.3.
  APPROVALS_AND_NOTIFICATIONS: [
    SmithersFeature.APPROVALS_PENDING_BADGES,
    SmithersFeature.APPROVALS_QUEUE,
    SmithersFeature.APPROVALS_INLINE_APPROVE,
    SmithersFeature.APPROVALS_INLINE_DENY,
    SmithersFeature.APPROVALS_CONTEXT_DISPLAY,
    SmithersFeature.APPROVALS_RECENT_DECISIONS,
    SmithersFeature.NOTIFICATIONS_TOAST_OVERLAYS,
    SmithersFeature.NOTIFICATIONS_APPROVAL_REQUESTS,
    SmithersFeature.NOTIFICATIONS_RUN_FAILURES,
    SmithersFeature.NOTIFICATIONS_RUN_COMPLETIONS,
  ],

  // Source: PRD section 6.6, Design section 3.6, Engineering section 3.3.
  TIME_TRAVEL: [
    SmithersFeature.TIME_TRAVEL_TIMELINE_VIEW,
    SmithersFeature.TIME_TRAVEL_SNAPSHOT_MARKERS,
    SmithersFeature.TIME_TRAVEL_SNAPSHOT_INSPECTOR,
    SmithersFeature.TIME_TRAVEL_SNAPSHOT_DIFF,
    SmithersFeature.TIME_TRAVEL_FORK_FROM_SNAPSHOT,
    SmithersFeature.TIME_TRAVEL_REPLAY_FROM_SNAPSHOT,
  ],

  // Source: PRD section 6.7, Design section 3.11, Engineering sections 2.3
  // and 3.4.
  WORKFLOWS: [
    SmithersFeature.WORKFLOWS_LIST,
    SmithersFeature.WORKFLOWS_DISCOVERY_FROM_PROJECT,
    SmithersFeature.WORKFLOWS_RUN,
    SmithersFeature.WORKFLOWS_DYNAMIC_INPUT_FORMS,
    SmithersFeature.WORKFLOWS_DAG_INSPECTION,
    SmithersFeature.WORKFLOWS_AGENT_AND_SCHEMA_INSPECTION,
    SmithersFeature.WORKFLOWS_DOCTOR,
  ],

  // Source: PRD section 6.8, Design section 3.7.
  AGENTS: [
    SmithersFeature.AGENTS_BROWSER,
    SmithersFeature.AGENTS_CLI_DETECTION,
    SmithersFeature.AGENTS_BINARY_PATH_DISPLAY,
    SmithersFeature.AGENTS_AVAILABILITY_STATUS,
    SmithersFeature.AGENTS_AUTH_STATUS_CLASSIFICATION,
    SmithersFeature.AGENTS_ROLE_DISPLAY,
    SmithersFeature.AGENTS_DIRECT_CHAT,
  ],

  // Source: PRD sections 6.9-6.10, Design sections 3.8-3.9.
  CONTENT_AND_PROMPTS: [
    SmithersFeature.TICKETS_LIST,
    SmithersFeature.TICKETS_DETAIL_VIEW,
    SmithersFeature.TICKETS_CREATE,
    SmithersFeature.TICKETS_EDIT_INLINE,
    SmithersFeature.TICKETS_SPLIT_PANE_LAYOUT,
    SmithersFeature.PROMPTS_LIST,
    SmithersFeature.PROMPTS_SOURCE_EDIT,
    SmithersFeature.PROMPTS_EXTERNAL_EDITOR_HANDOFF,
    SmithersFeature.PROMPTS_PROPS_DISCOVERY,
    SmithersFeature.PROMPTS_LIVE_PREVIEW,
    SmithersFeature.PROMPTS_SAVE,
  ],

  // Source: PRD sections 6.11-6.15, Design sections 3.10 and 3.16.
  SYSTEMS_AND_ANALYTICS: [
    SmithersFeature.SQL_BROWSER,
    SmithersFeature.SQL_TABLE_SIDEBAR,
    SmithersFeature.SQL_QUERY_EDITOR,
    SmithersFeature.SQL_RESULTS_TABLE,
    SmithersFeature.TRIGGERS_LIST,
    SmithersFeature.TRIGGERS_TOGGLE,
    SmithersFeature.TRIGGERS_CREATE,
    SmithersFeature.TRIGGERS_EDIT,
    SmithersFeature.TRIGGERS_DELETE,
    SmithersFeature.SCORES_AND_ROI_DASHBOARD,
    SmithersFeature.SCORES_RUN_EVALUATIONS,
    SmithersFeature.SCORES_TOKEN_USAGE_METRICS,
    SmithersFeature.SCORES_TOOL_CALL_METRICS,
    SmithersFeature.SCORES_LATENCY_METRICS,
    SmithersFeature.SCORES_CACHE_EFFICIENCY_METRICS,
    SmithersFeature.SCORES_DAILY_AND_WEEKLY_SUMMARIES,
    SmithersFeature.SCORES_COST_TRACKING,
    SmithersFeature.MEMORY_BROWSER,
    SmithersFeature.MEMORY_FACT_LIST,
    SmithersFeature.MEMORY_SEMANTIC_RECALL,
    SmithersFeature.MEMORY_CROSS_RUN_MESSAGE_HISTORY,
  ],

  // Source: PRD section 6.13, Engineering sections 3.0 and 5.
  MCP_INTEGRATION: [
    SmithersFeature.MCP_TOOL_DISCOVERY_FROM_SMITHERS_SERVER,
    SmithersFeature.MCP_RUNS_TOOLS,
    SmithersFeature.MCP_OBSERVABILITY_TOOLS,
    SmithersFeature.MCP_CONTROL_TOOLS,
    SmithersFeature.MCP_TIME_TRAVEL_TOOLS,
    SmithersFeature.MCP_WORKFLOW_TOOLS,
    SmithersFeature.MCP_AGENT_TOOLS,
    SmithersFeature.MCP_TICKET_TOOLS,
    SmithersFeature.MCP_PROMPT_TOOLS,
    SmithersFeature.MCP_MEMORY_TOOLS,
    SmithersFeature.MCP_SCORING_TOOLS,
    SmithersFeature.MCP_CRON_TOOLS,
    SmithersFeature.MCP_SQL_TOOLS,
  ],
} as const satisfies Record<string, readonly SmithersFeature[]>;

export type SmithersFeatureGroupName = keyof typeof SmithersFeatureGroups;

export const SmithersFeatures = Object.freeze(
  Object.values(SmithersFeature) as readonly SmithersFeature[],
);
